services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rescuesystem_db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "RescueSystem@123456Password"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "RescueSystem@123456Password", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: rescuesystem_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=RescueSystem;User Id=sa;Password=RescueSystem@123456Password;TrustServerCertificate=True;
    volumes:
      - aspnetcore_data:/app/data

volumes:
  sqlserver_data:
    driver: local
  aspnetcore_data:
    driver: local
