services:
  postgres:
    image: postgres:16-alpine
    container_name: rescuesystem_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RescueSystem@123456Password
      POSTGRES_DB: RescueSystem
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: rescuesystem_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=RescueSystem;Username=postgres;Password=RescueSystem@123456Password;
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - aspnetcore_data:/app/data

  caddy:
    image: caddy:2-alpine
    container_name: rescuesystem_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
    driver: local
  aspnetcore_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
